#source install-parameters.sh
echo "Edit /etc/openstack-dashboard/local_settings.py as follows:"
echo "*********"
echo "OPENSTACK_HOST = \"controller\"" 
echo "ALLOWED_HOSTS = ['*']" 
echo "CACHES = {" 
echo "    'default': {" 
echo "        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache'," 
echo "        'LOCATION': '127.0.0.1:11211'," 
echo "    }" 
echo "}" 
echo "*********"
echo "And then restart the following services" 
echo "service apache2 restart" 
echo "service memcached restart" 
echo "*********"
